package com.weer.weer_backend.dto;

import lombok.Data;

import java.time.LocalDateTime;
import java.util.Date;

@Data
public class HospitalDTO {
    private Long hospitalId;
    private Long equipmentId;
    private Long icuId;
    private Long emergencyId;
    private String hpid;          // 병원 식별 코드 (ID)
    private String name;          // 병원 이름
    private String address;       // 병원 주소
    private String city;          // 도시
    private String state;         // 시군구
    private String tel;           // 대표 전화번호
    private String erTel;         // 응급실 전화번호
    private Double latitude;      // 위도
    private Double longitude;     // 경도
    private LocalDateTime createdAt;       // 데이터 생성 일자
    private LocalDateTime modifiedAt;      // 데이터 수정 일자

    // Getters and Setters are generated by @Data
}
