version: '3.8'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # 기본 로그인 비밀번호 설정
      - GF_SECURITY_ALLOW_EMBEDDING=true  # iframe 임베딩 허용
    depends_on:
      - prometheus

volumes:
  grafana-data: