spring:
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  profiles:
    include: secret


springdoc:
  api-docs:
    path: /v3/api-docs  # OpenAPI 문서의 경로
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI의 경로
