spring:
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/WeER?characterEncoding=UTF-8&setTimezone=Asia/Seoul
    username: root
    password: root
  profiles:
    include: secret
  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics,prometheus

    metrics:
      export:
        prometheus:
          enabled: true

  data:
    redis:
      port: 6379
      host: 127.0.0.1

springdoc:
  api-docs:
    path: /v3/api-docs  # OpenAPI 문서의 경로
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI의 경로
